name: Preview Wiki from PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - docs/**
      - .github/workflows/publish-docs-wiki-preview.yml
concurrency:
  group: publish-docs-wiki
  cancel-in-progress: true
permissions:
  pull-requests: write
  contents: write
jobs:
  publish-docs-wiki-preview:
    runs-on: ubuntu-latest
    if: (contains(github.event.pull_request.title, '(docs)') || contains(github.event.pull_request.title, '[docs]'))
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@86138cbd6328b21d759e89ab6e6dd6a139b22270
        with:
          path: docs
          strategy: init
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `The [Documentation Wiki](/${context.repo.owner}/${context.repo.repo}/wiki) has been updated with a preview \
                    of the content of this PR because the title contains "(docs)" or "[docs]".  Note that this has overwritten the \
                    regular wiki contents for convenience.  Close this PR or manually run the 'Publish Docs Wiki' workflow to revert \
                    the wiki changes.`
            })